INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-cleansing-1', '로우 pH 젤 클렌저', 'OILOG LAB', 'cleansing', 18000, '/api/images/products/cleansing.png', '피지와 각질을 부드럽게 씻어내는 약산성 젤 클렌저.', 92, 'T존 피지량이 높아 저자극 세정이 우선이에요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-hydration-1', '라이트 워터 에센스', 'OILOG LAB', 'hydration', 24000, '/api/images/products/hydration.png', '유분 위에 얹혀도 무겁지 않은 저점도 수분 에센스.', 81, '유수분 밸런스를 맞추기 위한 가벼운 보습이 필요해요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-oil-control-1', '클레이 세범 패드', 'OILOG LAB', 'oil-control', 21000, '/api/images/products/oilcontrol.png', 'T존 피지를 흡착하는 클레이 성분 패드.', 88, 'T존과 U존의 피지 차이가 커서 부위별 케어가 효과적이에요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-sun-care-1', '매트 선 플루이드', 'OILOG LAB', 'sun-care', 19000, '/api/images/products/suncare.png', '산뜻하게 발리는 무기자차 선크림, 밀림 없는 매트 마무리.', 76, '피지가 많은 피부에는 무기자차 매트 제형이 잘 맞아요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-cleansing-2', '저자극 크림 클렌저', 'OILOG LAB', 'cleansing', 17000, '/api/images/products/cleansing.png', '건조함이 걱정될 때 쓰기 좋은 순한 크림 타입 클렌저.', 78, '세정력은 유지하면서 당김이 덜한 순한 제형을 원할 때 추천해요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-hydration-2', '진정 수딩 크림', 'OILOG LAB', 'hydration', 26000, '/api/images/products/hydration.png', '가벼운 에센스보다 밀도 있는 보습을 원할 때 좋은 수딩 크림.', 74, '건조함이 더 크게 느껴지는 날엔 밀도 있는 보습이 도움돼요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-oil-control-2', '살리실릭 토너 패드', 'OILOG LAB', 'oil-control', 22000, '/api/images/products/oilcontrol.png', '모공 속 피지까지 정돈해주는 산뜻한 토너 패드.', 80, '클레이 제형이 자극적으로 느껴질 때 대신 쓰기 좋아요.');
INSERT INTO products (id, name, brand, step, price, image_url, description, match_score, reason) VALUES ('product-sun-care-2', '수분 선크림', 'OILOG LAB', 'sun-care', 21000, '/api/images/products/suncare.png', '매트한 마무리보다 촉촉함을 원할 때 좋은 수분 선크림.', 70, '유수분기가 부족한 부위엔 촉촉한 제형이 더 편안해요.');
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-13', 'user-1', '2026-08-01T23:47:49.632Z', '', 34, 28, 45, 23, 32, 0.85, '건성', 'cactus');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-13', '이마', 52, 47, 50);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-13', '코', 43, 35, 40);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-13', '왼쪽볼', 19, 10, 15);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-13', '오른쪽볼', 24, 17, 21);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-13', '턱', 34, 29, 32);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-12', 'user-1', '2026-08-02T23:47:49.634Z', '', 36, 29, 53, 20, 33, 0.85, '건성', 'double-life');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-12', '이마', 59, 55, 57);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-12', '코', 50, 45, 48);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-12', '왼쪽볼', 22, 13, 18);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-12', '오른쪽볼', 21, 12, 17);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-12', '턱', 29, 22, 26);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-11', 'user-1', '2026-08-03T23:47:49.634Z', '', 39, 33, 58, 22, 37, 0.85, '건성', 'double-life');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-11', '이마', 61, 58, 60);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-11', '코', 58, 54, 56);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-11', '왼쪽볼', 29, 22, 26);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-11', '오른쪽볼', 22, 13, 18);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-11', '턱', 24, 16, 21);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-10', 'user-1', '2026-08-04T23:47:49.634Z', '', 42, 36, 60, 26, 40, 0.85, '중성', 'double-life');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-10', '이마', 60, 56, 58);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-10', '코', 63, 60, 62);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-10', '왼쪽볼', 37, 32, 35);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-10', '오른쪽볼', 28, 20, 25);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-10', '턱', 23, 14, 19);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-9', 'user-1', '2026-08-05T23:47:49.634Z', '', 45, 39, 57, 33, 43, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-9', '이마', 55, 49, 53);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-9', '코', 63, 59, 61);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-9', '왼쪽볼', 43, 40, 42);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-9', '오른쪽볼', 36, 30, 34);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-9', '턱', 27, 18, 23);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-8', 'user-1', '2026-08-06T23:47:49.634Z', '', 46, 41, 52, 39, 44, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-8', '이마', 49, 42, 46);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-8', '코', 59, 54, 57);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-8', '왼쪽볼', 45, 42, 44);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-8', '오른쪽볼', 43, 39, 41);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-8', '턱', 34, 28, 32);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-7', 'user-1', '2026-08-07T23:47:49.634Z', '', 46, 41, 47, 42, 44, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-7', '이마', 47, 38, 43);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-7', '코', 53, 46, 50);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-7', '왼쪽볼', 43, 39, 41);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-7', '오른쪽볼', 47, 44, 46);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-7', '턱', 42, 38, 40);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-6', 'user-1', '2026-08-08T23:47:49.634Z', '', 47, 40, 46, 43, 44, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-6', '이마', 50, 41, 46);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-6', '코', 50, 41, 46);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-6', '왼쪽볼', 38, 32, 36);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-6', '오른쪽볼', 47, 43, 45);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-6', '턱', 48, 45, 47);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-5', 'user-1', '2026-08-09T23:47:49.634Z', '', 46, 40, 50, 39, 44, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-5', '이마', 56, 49, 53);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-5', '코', 50, 41, 46);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-5', '왼쪽볼', 33, 25, 30);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-5', '오른쪽볼', 42, 37, 40);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-5', '턱', 49, 46, 48);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-4', 'user-1', '2026-08-10T23:47:49.634Z', '', 47, 40, 58, 35, 44, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-4', '이마', 65, 60, 63);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-4', '코', 55, 47, 52);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-4', '왼쪽볼', 31, 22, 27);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-4', '오른쪽볼', 37, 29, 34);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-4', '턱', 46, 42, 44);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-3', 'user-1', '2026-08-11T23:47:49.634Z', '', 49, 42, 66, 33, 46, 0.85, '중성', 'double-life');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-3', '이마', 71, 68, 70);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-3', '코', 63, 57, 61);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-3', '왼쪽볼', 35, 26, 31);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-3', '오른쪽볼', 34, 25, 30);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-3', '턱', 41, 34, 38);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-2', 'user-1', '2026-08-12T23:47:49.634Z', '', 52, 45, 71, 34, 49, 0.85, '중성', 'double-life');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-2', '이마', 74, 71, 73);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-2', '코', 71, 67, 69);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-2', '왼쪽볼', 42, 35, 39);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-2', '오른쪽볼', 35, 26, 31);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-2', '턱', 36, 28, 33);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-1', 'user-1', '2026-08-13T23:47:49.634Z', '', 55, 49, 72, 39, 53, 0.85, '중성', 'double-life');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-1', '이마', 72, 68, 70);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-1', '코', 76, 72, 74);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-1', '왼쪽볼', 50, 45, 48);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-1', '오른쪽볼', 40, 33, 37);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-1', '턱', 36, 27, 32);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-0-am', 'user-1', '2026-08-15T00:00:00.000Z', '', 57, 52, 70, 46, 55, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-am', '이마', 67, 61, 65);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-am', '코', 75, 72, 74);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-am', '왼쪽볼', 56, 53, 55);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-am', '오른쪽볼', 48, 43, 46);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-am', '턱', 39, 31, 36);
INSERT INTO measurements (id, user_id, captured_at, image_url, oil_coverage, oil_intensity, t_zone_score, u_zone_score, oil_score, confidence, skin_type, skin_character) VALUES ('measurement-0-pm', 'user-1', '2026-08-15T12:00:00.000Z', '', 58, 53, 66, 50, 56, 0.85, '중성', 'balance');
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-pm', '이마', 64, 57, 61);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-pm', '코', 73, 69, 71);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-pm', '왼쪽볼', 58, 55, 57);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-pm', '오른쪽볼', 53, 49, 51);
INSERT INTO zone_scores (measurement_id, zone, oil_coverage, oil_intensity, score) VALUES ('measurement-0-pm', '턱', 44, 36, 41);
INSERT INTO routine_events (id, measurement_id, product_id, note) VALUES ('routine-1', 'measurement-9', 'product-oil-control-1', '클레이 세범 패드로 교체');
INSERT INTO routine_events (id, measurement_id, product_id, note) VALUES ('routine-2', 'measurement-4', 'product-hydration-1', '라이트 워터 에센스 추가');
INSERT INTO routine_events (id, measurement_id, product_id, note) VALUES ('routine-3', 'measurement-0-pm', 'product-sun-care-1', '매트 선 플루이드로 교체');
